vich_uploader:
    db_driver: orm
    metadata:
        type: attribute
    mappings:
        media:
            uri_prefix: /medias
            upload_destination: '%kernel.project_dir%/public/media'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer