services:
  api:
    image: byidi/todo:latest
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro

  db:
    image: postgres:16.4-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    restart: unless-stopped
    ports:
      - "5432:5432"
    healthcheck:
      test: [
        "CMD", "pg_isready",
        "-d", "${POSTGRES_DB}",
        "-U", "${POSTGRES_USER}"
      ]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - db_data:/var/lib/postgresql/data:rw

volumes:
  db_data:
