name: CI

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
      - development
  pull_request: ~

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Setup env file
        uses: canastro/copy-file-action@master
        with:
          source: ".env.dist"
          target: ".env"
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Start services
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: |
            compose.yml
            compose.ci.yml
          services: |
            api
            db
      -
        name: Wait for healthchecks
        run: |
          timeout 60s sh -c ' \
          until docker ps | grep todo-actions-api-1 | grep -q healthy; \
          do echo "Waiting for container to be healthy..."; sleep 5; \
          done'
      -
        name: Check HTTP reachability
        run: curl -v --fail-with-body http://localhost/api
      -
        name: Run migrations
        run: |
          docker compose exec -T api \
          bin/console doctrine:migrations:migrate --no-interaction
      -
        name: Doctrine Schema Validator
        run: docker compose exec -T api bin/console doctrine:schema:validate
      -
        name: Remove File
        uses: JesseTG/rm@v1.0.3
        with:
          path: /path/to/something/you/want/to/delete
  lint:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      - name: "Install PHP with extensions"
        uses: "shivammathur/setup-php@v2"
      -
        name: "Install Composer dependencies"
        uses: "ramsey/composer-install@v2"
      -
        name: PHP CS Fixer
        run: vendor/bin/php-cs-fixer check --diff
      -
        name: PHPStan
        run: vendor/bin/phpstan
      -
        name: Hadolint
        uses: hadolint/hadolint-action@v3.1.0
      -
        name: Yamllint
        uses: ibiqlik/action-yamllint@v3
        with:
          config_file: .yamllint.yml
